.TH TCP_MASQ_OPENHOST 1 "TCPQuota Utilities" "FSF" \" -*- nroff -*-
.SH NAME
.B tcp_masq_openhost
\- Open a host for masquerading and accounting.
.SH SYNOPSIS
.B tcp_masq_openhost
.SH DESCRIPTION
Open the firewall for the computer/host the user is comming from,
and writes a entry to the mSQL masquerading table telling that
this host is using the TCP link.
.SH OPTIONS
none
.SH AUTHOR
Turbo Fredriksson, <turbo@tripnet.se>
.br
Martin Budsjoe, <marbud@tripnet.se>
