.TH TCPQUOTAADMIN 8 "TCPQuota Utilities" "FSF" \" -*- nroff -*-
.SH NAME
.B tcpquotaadmin
\- Administrate the TCP quota values.
.SH SYNOPSIS
.B tcpquotaadmin
.SH DESCRIPTION
Adds, removes and changes a users value in the allowed
and the masquerading mSQL tables.
.SH OPTIONS
none
.SH AUTHOR
Turbo Fredriksson, <turbo@tripnet.se>
.br
Martin Budsjoe, <marbud@tripnet.se>
