.TH TOPMASQ 1 "TCPQuota Utilities" "FSF" \" -*- nroff -*-
.SH NAME
.B topmasq
\- Show who is masqueraded right now.
.SH SYNOPSIS
.B topmasq
.SH DESCRIPTION
Keep scanning the masquerading table and show
the user and the destination of the external connect.
.SH OPTIONS
none
.SH SEE ALSO
.BR topnet (1)
.SH AUTHOR
Turbo Fredriksson, <turbo@tripnet.se>
.br
Martin Budsjoe, <marbud@tripnet.se>
